# This file is used by Render to configure the backend service.
# You can deploy by creating a new "Blueprint" service on Render
# and connecting it to your GitHub repository.
# Render will automatically detect and use this file.

services:
  # Simplified backend service
  - type: web
    name: ai-story-backend-v2
    env: node
    plan: free
    rootDir: apps/backend
    buildCommand: "npm install --only=production"
    startCommand: "node index.js" 